config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  root :to =>"homes#top"
  get "home/about"=>"homes#about"
  
  get "search" => "searches#search"
  

  resources :users, only: [:index,:show,:edit,:update] do
    # get "search" => "users#search"
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
    
  
  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
   resource :favorites, only: [:create, :destroy]
   resources :book_comments, only: [:create, :destroy]
  end
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
  
  validates :comment, presence: true
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  def create
    @book = Book.find(params[:book_id])
    @comment = current_user.book_comments.new(book_comment_params)
    @comment.book_id = @book.id
    @comment.save
    @bookcomment = BookComment.new
  end
  
  def destroy
    book_comment = BookComment.find(params[:id])
    book_comment.destroy
    @book = Book.find(params[:book_id])
  end
  
  private
  
  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end
  
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/views/book_comments/_comment.html.erb
<%= form_with model: [book, book_comment], local: false do |f| %>
  <%= f.text_area :comment, size: "85x5" %><br>
  <%= f.submit "送信" %>
<% end %> 

app/views/book_comments/_comments_view.html.erb
<table>
<% book.book_comments.each do |book_comment| %>
  <tr>
    <td>
      <%=link_to user_path(book.user.id) do %>
      <%= image_tag book_comment.user.get_profile_image, size:"50x50" %><br>
      <%= book_comment.user.name %>
      <% end %>
    </td>
    <td>
      <%= book_comment.comment %>
    </td>
    <td>
      <% if book_comment.user == current_user %>
      <%= link_to "Destroy", book_book_comment_path(book_comment.book, book_comment), method: :delete, class: "btn btn-sm btn-danger", remote: true %>
      <% end %>
    </td>
    </tr>
      <% end %>
</table>

app/views/book_comments/create.js.erb
$(".comments-view").html("<%= escape_javascript(render partial: 'book_comments/comments_view', locals: {book: @book, book_comments: @book.book_comments}) %>");
$(".comments-area").html("<%= escape_javascript(render partial: 'book_comments/comment', locals: {book: @comment.book, book_comment: @bookcomment}) %>");

app/views/book_comments/destroy.js.erb
$(".comments-view").html("<%= escape_javascript(render partial: 'book_comments/comments_view', locals: {book: @book, book_comments: @book.book_comments}) %>");